print " %r" %(True and True)
print " %r" %(False and False)
print " %r" %(1 == 1 and 2 == 1)
print " %r" %("test" == "test")
print " %r" %(1 == 1 or 2 != 1)
print " %r" %(True and 1 == 1)
print " %r" %(True or 1 == 1)
print " %r" %(False and 0 != 1)
print " %r" %("test" == "testing")
print " %r" %(1!=0 and 2 == 1)
print " %r" %(1 ==1 and (not ("testing" == 1 or 1 == 0)))
print " %r" %("chunky" == "bacon" and (not (3 ==4 or 3==3)))
